### ISSUE TITLE
Add option to ignore Vulnerabilities in Components with a low CPE confidence

### ISSUE THREAD

**Issue by NickHarvey2** [dependency-check/dependency-check-sonar-plugin#103]
Hey, I've been working within my org to get the OWASP dependency-check running as part of our release pipeline, but a significant hurdle has been that the vast majority (>90%) of vulnerabilities it identifies are false positives, having a low CPE confidence. Many of these simply could not be real vulnerabilities in our systems, such as a CVE from 2007, for a platform that didn't even exist at the time (misidentified as one that did).

This creates a lot of noise, and obscures several real, correctly identified vulnerabilities. I'd like to implement a project level configuration item for the plugin that allows project admins to have vulnerabilities in platforms identified with a low confidence to be ignored in SQ analysis. They would still be visible in the embedded HTML report, but would not generate security issues in the SQ report.

If this sounds acceptable, I will start working on it. Or if there are other ideas about how to implement something similar, that takes CPE confidence into consideration when generating SQ issues, I'm open to suggestions.

**Comment by Reamer** [comment]
Hi @NickHarvey2,
if this feature helps you and maybe others to work better with this sonar plugin, i can merge your Pull Request after a review.

**Comment by ewiegs4** [comment]
@NickHarvey2 OWASP dependency-check supports [a suppression file](https://jeremylong.github.io/DependencyCheck/general/suppression.html) for this exact use case, and is what I use for similar issues where internal components are mistaken for something else (using CPE suppression). Suppressions are excluded from the report data and therefore shouldn't impact SonarQube downstream.

**Comment by carlos-ferreira** [comment]
Hi actually agree with @NickHarvey2 

Some of the scans are way off.
Eg:

One of the projects i'm working on has the following dependencies:

![image](https://user-images.githubusercontent.com/472873/123630589-9e7b7e80-d80d-11eb-8816-1fa9770e3dd6.png)

These packages have zero known vulnerabilities, but since these are MySQL related dependencies, the dependency-check tool is marking them as vulnerable because MySQL had vulnerabilities:

![image](https://user-images.githubusercontent.com/472873/123630758-cec31d00-d80d-11eb-81c6-e11e2ca981a7.png)

The code to supress this false positive doesn't seem optimal to me
![image](https://user-images.githubusercontent.com/472873/123630921-07fb8d00-d80e-11eb-8674-5c63f912651a.png)
because, if i use another nuget package for MySQL is highly likely that i'll face the same problem.

If there was a way to use only ossindex via command line probably would solve the issue, at least regarding .net

**Comment by silver-mx** [comment]
> @NickHarvey2 OWASP dependency-check supports [a suppression file](https://jeremylong.github.io/DependencyCheck/general/suppression.html) for this exact use case, and is what I use for similar issues where internal components are mistaken for something else (using CPE suppression). Suppressions are excluded from the report data and therefore shouldn't impact SonarQube downstream.

How do you tell the sonar maven plugin/dependency-check-sonar-plugin which suppression file to use? Is there a configuration property for that?
