### ISSUE TITLE
Plugin 3.0.0 requires Java 11 - incorrectly?

### ISSUE THREAD

**Issue by hostalp** [dependency-check/dependency-check-sonar-plugin#611]
**Describe the bug**
The latest version (3.0.0) of this plugin appears to require Java 11.
However as it's claimed to support Sonar 8.9+ where Java 8 is still supported for the scanners: https://docs.sonarqube.org/8.9/requirements/requirements/#header-3 this requirement seems incorrect.
Our Maven projects that use Java 8 and this plugin are now getting an error about the plugin being compiled for Java 11.
We had to revert to the plugin 2.0.8 for now.

**Current behavior**
Maven output:
`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project xyz: The plugin [dependencycheck] does not support Java 1.8.0_322: org/sonar/dependencycheck/DependencyCheckPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

**Versions (please complete the following information):**
-   sonarqube 8.9.7 @ java 11.0.14
-   dependency-check-sonar-plugin 3.0.0
-   maven 3.6.3 @ java 8u322
-   sonar-maven-plugin 3.9.1.2184

**Comment by ianwilliams1** [comment]
A check of the history on the pom shows:
[Update sonar-plugin-api to 8.9.0.43852](https://github.com/dependency-check/dependency-check-sonar-plugin/commit/695882bb84a4b37e5f65c6b061fb074d6d9f1ad6)
```
-      <sonar.version>7.9.3.33150</sonar.version>
+      <sonar.version>8.9.0.43852</sonar.version>
```
followed by:
[Update jdk min version to jdk11](https://github.com/dependency-check/dependency-check-sonar-plugin/commit/56a06025a0156b2fd7b472a074e7d64cfaaaae90)
`+      <jdk.min.version>11</jdk.min.version>`

As noted in the initial report, [LTS 8.9.x scanners (evidently, hence plugins) remains at Java 8](https://docs.sonarqube.org/8.9/requirements/requirements/#header-3), while 9.x has been [bumped to 11](https://docs.sonarqube.org/latest/requirements/requirements/#header-3). 

So one of those changes (PR [Sonarqube 8 #445](https://github.com/dependency-check/dependency-check-sonar-plugin/pull/445)) is not consistent.

I do believe I recall the initial plan was 8.9.x was going to drop support for Java 8 but that was deferred to 9.x

**Preferred outcome:** Release a Java 8 compatible v2.0.9 and a Java 11 compatible v3.0.1, burn 3.0.0

**Comment by alwa** [comment]
> **Preferred outcome:** Release a Java 8 compatible v2.0.9 and a Java 11 compatible v3.0.1, burn 3.0.0

According to this projects README.MD file plugin 3.0.x is compatible with SonarQube 8.9 LTS and up. So I think Java 11 requirements should come in a later version (3.1.x?) for SonarQube 9 and up to avoid confusion.

**Comment by ianwilliams1** [comment]
It is SonarQube which governs the plugin compatibility and Min. Java Spec., not this [README.md](https://github.com/dependency-check/dependency-check-sonar-plugin#plugin-version-compatibility). They consider the plugin generically "a scanner".

JAVA Requirements (from SonarQube Documentation):
[SonarQube 9.x](https://docs.sonarqube.org/latest/requirements/requirements/#header-3)
[SonarQube 8.9.x](https://docs.sonarqube.org/8.9/requirements/requirements/#header-3)
[SonarQube 7.9.x](https://docs.sonarqube.org/7.9/requirements/requirements/#header-3)
[SonarQube 6.7.x](https://docs.sonarqube.org/6.7/Requirements.html)

<table style="width:100%">
  <tr>
    <th>Release</th>
    <th>Server</th> 
    <th>Scanner</th>
  </tr>
  <tr>
    <td>9.x</td>
    <td>11</td>
    <td>11</td>
  </tr>
  <tr>
    <td>8.9.x LTS</td>
    <td>11</td>
    <td>8,11</td>
  </tr>
  <tr>
    <td>7.9.x LTS</td>
    <td>11</td>
    <td>8,11</td>
  </tr>
  <tr>
    <td>6.7.x LTS</td>
    <td>8</td>
    <td>8</td>
  </tr>
</table>

[SonarCloud.io](https://docs.sonarcloud.io/appendices/move-analysis-to-java-11/) requires Java 11.

The original release plan was 8.9.x requirement was for ONLY Java 11 support on both server and scanner, but that was deferred to 9.x due to Covid.

Simply put, 3.0.0 breaks when running SonarQube 8.9.x LTS with Java 8 as the scanner platform.
The Defect request is for a SonarQube 8.9.x, Java 8 release of the plugin.
My suggestion is a Java 8 compatible 2.0.9 release and a Java 11 compatible 3.x release.
The plugin documentation (README) updated accordingly.

Alternatively, merely fix the specified [Minimum SonarQube Requirement](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/6100fb18e861a2d7f2de2652c9bf8fdec93f2686/sonar-dependency-check-plugin/pom.xml#L22) `<sonar.version>sonarqube-9.0.1.46107</sonar.version>`. That would make 3.0.1 only compatible with 9.x and prevent it from showing up as an update in 8.9.x releases, but also deny us the updated features. 8.9.x users on a Java 8 scanner platform already have to back it out.

**Comment by ianwilliams1** [comment]
Either way, 3.0.0 release should be discarded (to avoid unwanted breaking plugin updates) immediately. 
Corrected release(s) should be provided in the most suitable manner to the maintainer (I'd love a Java 8 - 2.0.9).

**Comment by alwa** [comment]
> Either way, 3.0.0 release should be discarded (to avoid unwanted breaking plugin updates) immediately. Corrected release(s) should be provided in the most suitable manner to the maintainer (I'd love a Java 8 - 2.0.9).

I have indications that 2.0.8 works with Java 8. Is it not working for you?

**Comment by Reamer** [comment]
I will release 3.0.1, which restores JDK8 compatibility, in a few minutes. Sorry for inconvenience.

**Comment by Reamer** [comment]
Plugin 3.0.1 has been released which restores JDK8 compatibility. When SonarSource/sonar-update-center-properties#276 is merged, you should see the new version via the marketplace. Of course, you can already manually put the version in the `extension/plugin` folder and use it.
